TRUNCATE TABLE public.tracking_events RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.tracking_metrics RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.tracking_snapshots RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.clicks RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.asaas_webhook_events RESTART IDENTITY CASCADE;